(defun fibo-generator ()
	(let ((x1 0) (x2 1))
		(lambda () (setq next (+ x1 x2))
				   (setq result x1)
				   (setq x1 x2)
				   (setq x2 next)
				   result
		)	
	)
)

(defun fibo-filter (arr)
	(setq get-next (fibo-generator))
	(do ((result nil)
		 (idx (funcall get-next) (funcall get-next))
		)
		((>= idx (length arr)) result)
		(setq result (append result (list (nth idx arr))))
	)	 
)